;[1mresources/champs/parsing_breaker/header/missing_quote_comment.s:8:11: [1m[31merror: [0m[1munexpected expression in .name declaration
;[0m.comment "description
;          [1m[32m^[0m[1m[32m~~~~~~~~~~[0m
;[1mresources/champs/parsing_breaker/header/missing_quote_comment.s: [1m[35mwarning: [0m[1m'.comment' is undefined (set to 'name and comment generated by asm')
;[0m1 warning and 1 error generated.

.name "zork
.comment "description


live %1