;[1mresources/champs/parsing_breaker/header/too_long_name.s: [1m[35mwarning: [0m[1m'.name' is undefined (set to 'no name')
;[0m[1mresources/champs/parsing_breaker/header/too_long_name.s: [1m[35mwarning: [0m[1m'.comment' is undefined (set to 'name and comment generated by asm')
;[0m2 warnings generated.
